### ISSUE TITLE
UpComing Events List

### ISSUE THREAD

**Issue by QuentinLeroyTSE** [studentenhuisDS4/ds4reboot#145]
Issue: We never remember what is the exact date of the upcoming events.

New tab where people can create _new event_ with a start` date, a title, a description, and a link to the event page.
The list should be ordered by date from the earliest event to the latest.

**Comment by davidzwa** [comment]
#110

**Comment by davidzwa** [comment]
I added an ImageField database column for each event. This should allow us to upload a thumbnail for each event.

**Comment by davidzwa** [comment]
This issue is superseded by Google Calendar integration. Closing
