### ISSUE TITLE
Beer Sound

### ISSUE THREAD

**Issue by QuentinLeroyTSE** [studentenhuisDS4/ds4reboot#146]
**Marcus and Jarno idea:**
Play a sound (_ask Jarno for it_) each time someone takes a beer and click on "+" on the bierlijst. 
Jarno wants to connect a loudspeaker to the GR computer and hang it in the opposite top corner of the room.
Several sounds can be recorded and played in random order.

**Comment by davidzwa** [comment]
[Link to SO page](https://stackoverflow.com/questions/8489710/play-an-audio-file-using-jquery-when-a-button-is-clicked)

**Comment by davidzwa** [comment]
Fixed by #148
