### ISSUE TITLE
Database backup cronjob

### ISSUE THREAD

**Issue by damienallen** [studentenhuisDS4/ds4reboot#55]
We should have a frequent backup of the database using the built-in `dumpdata` management command. Need to figure out frequency and retention time.

**Comment by damienallen** [comment]
Maybe there is a library that can do rolling backups automatically, will investigate.

**Comment by davidzwa** [comment]
Where to back up to is more important of a question.

**Comment by davidzwa** [comment]
Docker implementation on server.
