### ISSUE TITLE
Eetlijst num_eating can be incorrect

### ISSUE THREAD

**Issue by damienallen** [studentenhuisDS4/ds4reboot#82]
Happened on the same day Jefferson had 250X next to his name. Probably another issue of the order of "save" statements.

**Comment by davidzwa** [comment]
@damienallen Will have to take a look at it Wednesday evening, ok?

**Comment by JBmiog** [comment]
Wasn't Karel pressing 250 times during instemming?

**Comment by davidzwa** [comment]
I think it is related to AJAX and server - client communication. Does AJAX check if the packet arrives multiple times? Could it maybe be that a key was stuck on the keyboard on the GR-pc?

**Comment by JBmiog** [comment]
I still believe it was karel:D
