### ISSUE TITLE
House order not solid

### ISSUE THREAD

**Issue by davidzwa** [studentenhuisDS4/ds4reboot#83]
According to Melle/Ilse/Marloes the order of Melle and Marloes changes sometimes.

This maybe has to do with move-in date. Ordering should occur by user_id.

**Comment by damienallen** [comment]
Then you lose all flexibility to adjust the order. So if people are added in the wrong order then they have to be deleted and readded (along with their balance, boetes, etc).

For now you can just make a 1 day difference in move-in dates.

**Comment by davidzwa** [comment]
I instructed Jeffrey on how to change the entry date. The issue then becomes to change the entry date via the profile page which is planned to be added.
